server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/Manit-Kumar-Panda/spring-cloud-config-server-repository.git
          default-label: master
          username: Manit-Kumar-Panda
          password: ENC(TIKMWIKcMrmjRmPP73q6diKeyJdzb+ie17xQiRfFZoDM9cwdmb/WkkKPCQJgik7Ex9Z9ZZHetGx4xD1dLLsCcms+VE8074VcJW14ncCW7m0=)
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: username
      password: password

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
    com.ulisesbocchio.jasyptspringboot: DEBUG

jasypt:
  encryptor:
    password: ${S}
