server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/Manit-Kumar-Panda/spring-cloud-config-server-repository.git
          default-label: master
          username: XYZ
          password: XYZ
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
